### ISSUE TITLE
year Date is shown as 2564 when language of device is thai. 

### ISSUE THREAD

**Issue by leukhe** [minvws/nl-covid19-coronacheck-app-ios#106]
### when the iphone is set to language thai, the year is formatted in thai year

It really is 2565 in thailand, so that is correct. However this confuses ANY european user.(in my case the german restaurant i sat down in)  The data should ALWAYS be in european date format DD-MM-YYYY 

E.g. 

### To Reproduce
1. Go to 'language settings '
2. Set language to ไทย  (thai) 
3. Restart corona check app. '
4. in the international tab, the vaccination year and the birthdate are in thai year ( currently it is 2565 in thailand.). Note that thai passports show European year. 

### Expected behavior
All dates should be in european format. (android is ok)

**Comment by leukhe** [comment]
Workarround: Set device langague not to thai...

**Comment by iandundas** [comment]
Thanks for reporting this, I have created a ticket in our bug tracker to pick this up 👍🏻
