### ISSUE TITLE
App shows 1/1, 2/1, 3/1 vaccinations

### ISSUE THREAD

**Issue by timcooijmans** [minvws/nl-covid19-coronacheck-app-ios#113]
### Describe the bug, issue or concern

In the international section of the app, my app shows both on the overview and the QR-code “scroller” that I have 3/1 vaccinations. This is also reflected in international the QR-code and seen by other international scanners. 

### To Reproduce
1. Have received 3 vaccinations
2. Go to the international overview 
3. See that 3/1 vaccinations are received

### Expected behavior
The app shows 1/3, 2/3 and 3/3 for the vaccinations.

### Screenshots
![5D8B9C5E-D3D4-48A6-895A-B2BCC6228507](https://user-images.githubusercontent.com/3218488/153659127-c174e31e-9b46-41bb-852e-24943bedcad6.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 
 - OS: iOS 15.2.1
 - Browser: Safari 
 - App Version: 2.8.0 build 5949

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by Rool** [comment]
This is correct behaviour.

When you had Corona before your first vaccination and/or Janssen was your first vaccination. Then `1/1` is the first one and all vaccination that follow will lead into `2/1`, `3/1`, etc.

[https://coronacheck.nl/nl/faq/2-7-hoe-voeg-ik-mijn-boosterprik-toe-aan-mijn-vaccinatiebewijs/
](https://coronacheck.nl/nl/faq/2-7-hoe-voeg-ik-mijn-boosterprik-toe-aan-mijn-vaccinatiebewijs/
)

**Comment by timcooijmans** [comment]
Ok, thanks. I can understand the technicalities. This causes a lot of confusion internationally because having 3 out of 1 vaccination is very strange or I dare to say mathematically wrong.
