### ISSUE TITLE
Add support for deeplinking

### ISSUE THREAD

**Issue by maurice-close** [minvws/nl-covid19-coronacheck-app-ios#15]
### Add deeplinking support

To integrate with other apps, please add deeplinking so it is possible to open the CoronaCheck app on a certain screen from another app or from a webpage. For example:

coronacheck://makeappointment to open the app on the 'Make appointment' screen
coronacheck://createqr to open the app on the 'create QR' screen
coronacheck://showqr to open the app on the the screen that shows the QR

Or:

coronacheck://createorshowqr which shows the create QR if none was created, or if already created it shows the QR code directly. If there are multiple QRs available (is that possible?), then show a selection screen.

### Register a domain

Registering a domain would improve the user experience even more (this can be done for both iOS and Android). For example when https://downloadcoronacheckapp.rijksoverheid.nl/ is registered, it is possible to create the behaviour that when URL is visited on a phone that doesn't have the app installed, it will redirect to the download page. When the app is installed, visiting this url will open the app.

### Rationale

Our product (http://www.thecloseapp.com) is the communication platform between the organizers and the visitors of the FieldLab events. We send instructions to visitors where to download and install the Corona Check app and when to open and show the QR code. The user experience would be greatly improved if we could link directly to screens in the app. This improves the conversion to the Corona Check app, makes it easier to use for visitors of the FieldLab event and thus makes it less error prone for visitors to use.

**Comment by ijansch** [comment]
This was a great idea and is currently being implemented for the next release. The documentation can be found here: 

https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/docs/app-deeplinks.md
