### ISSUE TITLE
Sync CoronaCheck releases to GitHub before roll out.

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-coronacheck-app-ios#36]
Currently CoronaCheck version 2.1.0, 2.1.1 and 2.1.3 are rolled out through the App Store, but not yet available in this GitHub repo. This undermines the open-source principals. Source code should be made first available on GitHub, before pushing to Apple and rolling out, so that it can be independently checked.

_Ping @Rool @iandundas_

**Comment by iandundas** [comment]
Hi @EwoutH, you're right that it should now be available, I'll push the code tomorrow.

**Comment by iandundas** [comment]
https://github.com/minvws/nl-covid19-coronacheck-app-ios/pull/37
