### ISSUE TITLE
'Fietsje' takes few seconds to start moving on national QR code, making hard to check if its screenshot

### ISSUE THREAD

**Issue by Markus92** [minvws/nl-covid19-coronacheck-app-ios#38]
### Describe the bug, issue or concern
See title, the little bike takes few seconds to start moving on national QR code, and pauses between loops

### To Reproduce
1. Have an older model iPhone to make it more noticeable (6s, SE 2020)
2. Display national QR code
3. Observe the screen can remain static during the time it takes to scan the QR code, there's a pause when it loops.

### Expected behavior
Same as international QR code: always have some movement (multiple people on the conveyor belt). don't loop with a break in between. Or have multiple bikes that loop along the screen instead of one with a start/stop motion.

### Screenshots
N/A.

### Additional context
This has the potential to undermine the security of the app. The scanner app is fast enough that there could not be any movement during the 'scanning' period and bouncer might not have time to observe the movement as they're checking IDs.

Not as much of an issue on Android as screenshots aren't as easily made.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by Rool** [comment]
I'll see if I can change the timing of the animation, so the cyclist is nonstop cycling.

There will be a new animation replacing the cyclist in the near future, the animator is working on that.
