### ISSUE TITLE
Onschuldige tikfout Sources/CTR/Infrastructure/Services/WallerManager.swift: GreenCrards

### ISSUE THREAD

**Issue by tinus-github** [minvws/nl-covid19-coronacheck-app-ios#39]
### Describe the bug, issue or concern
Ik was de code aan het lezen, ik zag in Sources/CTR/Infrastructure/Services/WallerManager.swift deze regel (nu regel 250):

					for case let greenCard as GreenCard in greenCrards.allObjects {

Ik begreep niet helemaal hoe je dit zou kunnen compileren met de 'greenCrards' tikfout. Maar ik zie dat dit ook al in de regel daarvoor misgetikt is:

				if let greenCrards = wallet.greenCards {
					for case let greenCard as GreenCard in greenCrards.allObjects {
    ...

					}
				}

Zo is het dus een wat vreemde maar verder onschuldige tikfout.

**Comment by Rool** [comment]
Thanks for spotting this typo.
Will be fixed with the next sync.
