### ISSUE TITLE
International QR code 1/1 dose instead of 2/2. 1 dose hospital 1 dose ggd

### ISSUE THREAD

**Issue by retaildesk** [minvws/nl-covid19-coronacheck-app-ios#40]
### Describe the bug, issue or concern

When you get 1 dose in the hospital and one dose by the GGD the international qr code says 1/1 dose instead of 2/2.

E.g. 

### To Reproduce
1. Get vaccination in hospital
2. Get second vaccination by GGD
3. After few days check mijn.rivm.nl in my case both vaccinations are listed
4. Receive vaccination data. When i receive the vaccinations i see both vaccinations listed by RIVM and the last one double. So in total 3 records. 2x Rivm, 1x GGD (last dose). 
5. Go to international QR code and press info button. Only 1/1 dose is listed.

### Expected behavior
Since mijn.rivm is having 2 vaccination the international qr code should represent both doses.

### screenshots
![IMG_5471](https://user-images.githubusercontent.com/67142861/125613213-6a69ed92-cfbc-4be0-8f16-4923b5bee963.PNG)
![IMG_5470](https://user-images.githubusercontent.com/67142861/125613222-ce0f9f07-2645-416a-885f-d68dfd244fd1.PNG)

**Desktop (please complete the following information):**
 - OS: IOS latest version
 - Coronacheck 2.1.7

**Smartphone (please complete the following information):**
 - Device: iPhone 12

### Additional context
Tried uninstalling and reinstalling app. 

### Governance
- [ x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by marcokrikke** [comment]
I've received two vaccinations via GGD and see them twice in the app (RIVM + GGD).

When comparing the vaccination details with coronacheck.nl, data seems to be missing or inconsistent in the iOS app. Also within the app, data is incosistent between the vaccination details and the International QR Code details.

- GGD: 2nd dose in app says 'no' with last doses, while it is. The 'no' is confusing, it might lead to users believing their QR code is invalid. The international QR code does say 2/2 doses
- RIVM certificate identifier does not match, but seems to be different every time I try, both on the website and in the app?
- RIVM vaccine manufacturer and type mentioned in the app, but not on coronacheck.nl

### GGD

App: 
![GGD iOS app](https://user-images.githubusercontent.com/1352315/126960736-9941de0f-ac04-41bd-a96e-eea5a5c5e6cb.jpg)

Website:
![GGD coronacheck.nl](https://user-images.githubusercontent.com/1352315/126960788-5fef4049-3d60-477b-b414-0c0a392e0bd2.png)

### RIVM

App:
![RIVM iOS app](https://user-images.githubusercontent.com/1352315/126961744-a718a25d-4d0c-4736-9b61-f423fa3febb6.jpg)

Website:
![RIVM coronacheck.nl](https://user-images.githubusercontent.com/1352315/126961799-e8b6a591-0d08-413b-a540-0ce686aaa48e.png)

### QR in app

![IMG_1661](https://user-images.githubusercontent.com/1352315/126963251-3258de27-2073-4ebb-90d2-de95d44d192c.jpg)

**Comment by retaildesk** [comment]
My issue is solved with the last version of the app.

**Comment by iandundas** [comment]
Good to hear, thanks for updating us
