### ISSUE TITLE
'Add certificate' doesn't work when default browser is other than Safari

### ISSUE THREAD

**Issue by ingebeumer** [minvws/nl-covid19-coronacheck-app-ios#41]
'Add certificate' in CoronaCheck app doesn't work when the default browser is other than Safari. 

Steps to reproduce:
1. Change the iPhone's default browser to Edge Canary (also observed on Edge Dev). 
![20210720_141439000_iOS](https://user-images.githubusercontent.com/40343254/126340989-3355d6d1-d9b3-4981-a22f-563f126d69c4.png)
2. Start app CoronaCheck.
3. In menu choose 'Add certificate' and choose the kind of certificate you need to add.
![20210720_141958000_iOS](https://user-images.githubusercontent.com/40343254/126341227-906c830f-ceae-4ed8-b5dd-badd7d75ad78.png)
4. Choose 'Log in with your DigiD'.
5. Browser (default browser Edge Canary) is opened, go through DigiD login process.
6. Login process ends with blank page in browser (note this is different in Safari browser, there I got a message asking to switch to CoronaCheck app, which after confirmation switches to the app and loads the certificate).
![20210720_142125000_iOS](https://user-images.githubusercontent.com/40343254/126341328-4357f7e0-2be9-42e2-8e19-fc527e5f9a34.png)
7. Switch back to CoronaCheck app. The wait signal keeps spinning forever and nothing is loaded. No error messages observed.
![20210720_142212000_iOS](https://user-images.githubusercontent.com/40343254/126341407-b4b33b49-8991-4b75-9c96-8aa86ddd3011.png)
 
Worked around this by temporarily switching Safari to be the default browser, but I expect the app to work with Edge browser as well. Later switched default browser back to Edge Canary, and no issue is observed in showing certificates that are already there. So only with adding a certificate.
Observed on iPhone 11 Pro, software version 14.6, default Edge Canary browser version 93.0.953.0 (also observed by others with default Edge Dev browser) 
 
Please review as CoronaCheck app on iPhone is eligible for improvement.
 
Thank you and kind regards, inge
 
- [ x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by Rool** [comment]
Thanks for the report, we'll be investigating this default browser issue.

**Comment by ingebeumer** [comment]
Thank you @Rool, credits to my colleague Rob who mentioned it and this was indeed the issue I was experiencing.

**Comment by marcokrikke** [comment]
FYI, works for me with Chrome as default browser on iOS 14.7.

**Comment by Rool** [comment]
I changed the implementation and try to use the default browser. Confirmed it works for Chrome, Edge and Brave. 
![IMG_0045](https://user-images.githubusercontent.com/344216/128826323-639eb2fc-e886-407a-8c33-20b79b4de42a.PNG)

**Comment by Rool** [comment]
Should be fixed in release 2.2.1 and newer.
