### ISSUE TITLE
App shows 1/1 dose for dual-vaccinated after covid

### ISSUE THREAD

**Issue by CyBeRoni** [minvws/nl-covid19-coronacheck-app-ios#64]
### Describe the bug, issue or concern

The app currently shows 1/1 vaccinations after retrieving two vaccinations if a certificate of recovery is also present. This will certainly cause problems with countries that require two vaccinations even if recovered, e.g. UK. This is new behaviour introduced (I guess) some time in the past week or so. 

E.g. 

### To Reproduce
1. Get covid and recover
2. Get fully vaccinated (2 shots)
3. Add Recovery certificate
4. Add Vaccination certificate
5. See 1/1 dose instead of 2/2 doses.

### Expected behavior
I expect the vaccination certificate to always show the exact amount of doses received (and retrieved from GGD/RIVM), regardless of any other information being available. I.e., if two (or three with a booster) shots were received the app should **always** show that amount. The **only** time information on recovery should be used is if a single shot was received.

### Screenshots
n/a

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15
 - Browser: Safari
 - Version: most recent

### Additional context
I switched phones this week and the old phone still shows 2/2 from a certificate retrieved before this week. 

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
We released a fix for your case. If you load your certificate again from the source (plus button in the top right of the screen), you should now get a 2/2 in this situation. 

I’ll close the issue. Feel free to reopen it if you still have the issue.
