### ISSUE TITLE
Changing time on iOS allows QR to be shown

### ISSUE THREAD

**Issue by abcdan** [minvws/nl-covid19-coronacheck-app-ios#67]
### Describe the bug, issue or concern

If you don't have a valid QR yet, for example, it has been 4 days since your 2nd vaccination it currently shows that the QR will become on x date. But if you change the time to the future in your phone's settings, the view QR button becomes clickable and you can see the QR code.

### To Reproduce
1. Don't have a valid NL QR yet.
2. Change the time to the future in the phone's settings
3. Click the view QR button.
4. Your code is available.

### Expected behavior
The code should not be available.

### Screenshots
Before the time was changed:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/15849319/136334177-c1cedb7c-7d0f-419a-812a-f071c06f17a3.png">

After the time was changed:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/15849319/136334075-ee43c664-64e0-4cf5-9492-604959ec77fc.png">

_Note, this is NOT my phone. I already have a valid QR. Nor is the person abusing this app's behaviour._

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS15
 - Version: latest version from the app store.

### Additional context
A way to fix this issue. Is connect to the API and ask what time it is over there instead of relying on the local time of the device.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by iandundas** [comment]
Hi Daniël, thanks for your report,

Yes it is correct that you can get it to show a QR code, however the QR code is not scannable by the [CoronaCheck Scanner](https://apps.apple.com/nl/app/scanner-for-coronacheck/id1549842661?l=en). See also the “Controleer de tijd” message that you see in your screenshot.

i.e. it’s not valid for entry

**Comment by abcdan** [comment]
Ah, awesome! Thanks! :)

**Comment by abcdan** [comment]
Is er niet een manier om het dan ook onmogelijk te maken de QR d'r bij te pakken? Dat zou het denk voor de gebruiker _net_ nog wat duidelijker maken?

**Comment by iandundas** [comment]
Closing as first question was answered - feel free to open another issue if you like :)
