### ISSUE TITLE
"universal link" feature for event-organisers

### ISSUE THREAD

**Issue by AFCAjaxNV** [minvws/nl-covid19-coronacheck-app-ios#8]
[Input ICTRecht tijdelijke wet testbewijzen covid-19 12032021.pdf](https://github.com/minvws/nl-covid19-coronacheck-app-ios/files/6137001/Input.ICTRecht.tijdelijke.wet.testbewijzen.covid-19.12032021.pdf)

Please find the (dutch) opinion article about an improvement to the coronacheckapp to support large venues and their organisers. This case is about AFC Ajax NV / Johan Cruijff Arena, but multiple large event-organisers and ticket-companies would be able to support this flow.

Our stadium is ready for 55.000 fans, the current coronacheck-app lacks integration with the organiser and fans. 
In the current proposal it would require us to employ at least 250 (untested) extra stewards to manually scan-and-verify all credentials. Also if credentials don't match or no test is done the fan will only find out at the location, we think that should be much more in advance to prevent unnecessary travel. 

Our concrete request is support "universal links" for the coronacheck app (i.e like "Idin" and "Ideal").
fan-flow:
* Fan buys a ticket (or is seasonticket holder) in Ajax-app
* Fan receives notification in ajax-app with ticket (not displaying QR-Code)
* 24 hours before event-start fan is notified in Ajax-app to setup/activate coronacheckapp
* when fan clicks on the "activate link" a universal link is called with fan's initials, birthday-day and birthdate-month
* coronacheck app opens automatically
* coronacheck app asks for permission to send OK to ajax-app
* coronacheck app returnURL to ajax-app with "OK" notification.
* ajax-app never sends the coronacheck data, OK notification is only to unlock the QR at the local device! (if user would switch device or share ticket they are forced to do the activation process again!)
* ajax-app displays QR code for fan when arriving at stadium ground

This way is in our opinion according to all privacy laws and this principle has been tested up to 12K fans during the start of the season with 5 matches (only corona questions instead of coronacheck app).

**Comment by jordibruin** [comment]
While I understand the rationale, there is not guarantees that the Ajax app will never send any of the corona check data correct? That's what makes this difficult to implement I think.

**Comment by MaxReckers** [comment]
Ajax-app will never receive any "positive" measurement, that is controlled by the corona-check app (which only will send a "OK" if valid). If invalid there will be many posibilities (invalid test-date, positive test, wrong initial, wrong birth-month, wrong birth-year)

**Comment by jordibruin** [comment]
Ha @MaxReckers , oude bekende. Wij hebben vroeger toen ik nog bij Triple zat nog samen dingen gedaan met Google Glass! Kleine wereld! 🙂 

On topic:
Fair point regarding the possibilities for a 'negative' measurement, I hadn't thought of it in that way. Will read up some more on the project.

**Comment by ijansch** [comment]
Thanks for this suggestion! Although it’s technically probably not impossible to connect the two apps, the difficulty is that even a simple ‘ok’ is a ‘bijzonder persoonsgegeven’. Therefor, it’s currently not up to us as engineers; the discussion is passed through and will be addressed on the policy / legal table. So I suggest to close this issue for now awaiting discussions elsewhere.

(Something to consider in the mean time: an ‘ok’ as suggested would have to get some form of signature or authentication, to prevent someone from manually constructing the universal link. The site association file only limits which app can open the link, not which one can call it)

**Comment by MaxReckers** [comment]
Hi Ivo, As this is a real showstopper for us I would kindly ask your support to not close this issue and find a technical solution. 
It is just not possible to have a crowd this big without proper guidance from the organiser perspective. 
Also very tough that Freek has never been able to address this issue internally.

Our privacy lawyers do not agree with your "bijzonder persoongsgegeven" statement and are prepared and ready for the "table", anytime.

Technically there are multiple solutions we can work out, depending if you want to keep all communication between the apps or involve a backend.
1. (all local) -> public/private key encryption with a nonce which is stored in Ajax app after submission
2. (mixed) -> send the QR-token, use a sdk/api with your current corona-check app technology

Can we consider a technical meeting?

Regards,

Max

**Comment by ijansch** [comment]
The deeplink has meanwhile been implemented and its documentation can be found here: 

https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/docs/app-deeplinks.md

Other enhancements are currently being discussed, but since this is the original ticket from April, I'll close this one for now.
