### ISSUE TITLE
App should not hide international QR codes after screenshot is taken

### ISSUE THREAD

**Issue by CyBeRoni** [minvws/nl-covid19-coronacheck-app-ios#80]
### Describe the bug, issue or concern

The app hides the QR codes for three minutes after a screenshot is taken. This is presumably because the NL codes change every so often (3 minutes?) to prevent fraud with these codes. This is fine.

However, the app also hides the international QR codes, even though those do not change, or at least not as rapidly as the NL codes, which makes the 3 minute lockout period a nuisance. Additionally, the app informs you that "a screenshot is not a valid certificate" which in the case of the international codes is patently false as no requirement is made for the certificate to be presented in an app by (EU) 2021/953.

The reason this is a nuisance is that some countries are now requiring that QR-codes be uploaded to a system before travel to that country is authorised. For example, Singapore requires this as part of their Vaccinated Travel Lane program, where you get a travel authorisation from their system before you are able to board by uploading the QR code along with some other personal details ahead of time. This can be done in the form of a screenshot from your respective DCC app, but the Dutch CoronaCheck App frustrates this process by unnecessarily hiding the codes after a screenshot is made. 

### To Reproduce
1. Open app
2. Open International QR code
3. Take screenshot
4. Observe code is hidden for 3 minutes.

### Expected behavior
I expect the NL code to be hidden as a fraud prevention measure. I do not expect the international code to be hidden.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.1
 - Browser N/A
 - App Version 2.4.0 (4211)

### Additional Information
I don't own an Android phone but as I understand it, on Android creating a screenshot is entirely prevented and the mechanism of hiding on iOS is done because iOS does not offer the ability to prevent screenshots from being taken. The same applies: international codes should be screenshot-able.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
Despite the block on the QR, the screenshot is still saved, so it can be uploaded. Or do you have to upload it twice?

also note that countries that accept the dcc should respect the dcc terms, which state that storing a dcc to validate it is not permitted so be careful with uploading a dcc to a server.

**Comment by CyBeRoni** [comment]
> Or do you have to upload it twice?

Before last week or so, Singapore required two certificates to be uploaded (one for each shot). Many countries (ourselves included up until very recently) do not provide that so they have changed that requirement but I expect they will not be the only ones with such a requirement, and if all countries are to start offering one certificate per shot as we do now that requirement may return.

**Comment by ijansch** [comment]
Unrelated to this issue, but good to know: In the version that's currently in the store you can get QR codes for both shots.
