### ISSUE TITLE
Some falsified EU DCC are still not rejected by CoronaCheck _scanner_

### ISSUE THREAD

**Issue by HenkPoley** [minvws/nl-covid19-coronacheck-app-ios#84]
For which there is no issue tracker.. Neither for the DCC Scanner, for border patrol.

Example leaked EU DCC QR code: https://github.com/ehn-dcc-development/hcert-spec/discussions/105#discussioncomment-1591595

Already reported it here about a week ago: https://twitter.com/henkpoley/status/1457713831514451972?s=21

Since the list is dynamically downloaded, I suppose that report never really went anywhere (going back to, no public issue tracker).

**Comment by HenkPoley** [comment]
Some more from here: https://github.com/denysvitali/covid-cert-analysis/blob/master/LEAKED.md

Still scans: 

* [samples/leaked/043.txt](https://github.com/denysvitali/covid-cert-analysis/blob/master/LEAKED.md#samplesleaked043txt)
* [samples/leaked/040.txt](https://github.com/denysvitali/covid-cert-analysis/blob/master/LEAKED.md#samplesleaked040txt)
* [samples/leaked/033.txt](https://github.com/denysvitali/covid-cert-analysis/blob/master/LEAKED.md#samplesleaked033txt)
* [samples/leaked/014.txt](https://github.com/denysvitali/covid-cert-analysis/blob/master/LEAKED.md#samplesleaked014txt)
* [samples/leaked/009.txt](https://github.com/denysvitali/covid-cert-analysis/blob/master/LEAKED.md#samplesleaked009txt)

**Comment by Rool** [comment]
Thanks, I have forwarded this to our security team, will keep you posted.

**Comment by HenkPoley** [comment]
I'll close this as "works as intended". 

Meaning, the receiving end is supposed to check the passport matches the EU DCC QR-code.
