### ISSUE TITLE
Details button Dutch QR Code screen not working

### ISSUE THREAD

**Issue by daannijkamp** [minvws/nl-covid19-coronacheck-app-ios#98]
### Describe the bug, issue or concern

After updating to version 2.7.0, the details button of the Dutch QR code screen is not working.
If you press on the details button, it will have the "pressed state". But no detail screen appears.

Note: the international QR code details button does work.

Details: 
- Vaccination certificate (3 doses)
- iOS 15.2
- iPhone 13 Pro
- App version 2.7.0 (build 5552)

### Governance
- [X ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by Rool** [comment]
Thanks for this report.
We noticed this morning that you could not visit the details of the dutch QR if you upgraded from the 2.6.x version.
You can see them if you refetch your vaccinations / recoveries / tests. 

We are working on a fix in a 2.7.1 hotfix that is currently being reviewed by Apple.

**Comment by daannijkamp** [comment]
@Rool thanks! After updating to 2.7.1, the details button is working again.
